-- ============================================================================
-- Seed inicial: vuelca el menú completo de Empapados a la base de datos.
-- Ejecutar UNA SOLA VEZ después de crear las tablas (schema.sql), para no
-- perder el trabajo de armado del menú ya hecho. Ver README para el paso a paso.
-- ============================================================================

-- Categorías
INSERT INTO categories (id, label, sort_order) VALUES ('escoge-tu-box', 'Escoge tu Box', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, label, sort_order) VALUES ('box-cheddar', 'Box Cheddar', 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, label, sort_order) VALUES ('conos', 'Conos', 2) ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, label, sort_order) VALUES ('box-burger', 'Box Burger', 3) ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, label, sort_order) VALUES ('sandwich', 'Sandwich', 4) ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, label, sort_order) VALUES ('completos', 'Completos', 5) ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, label, sort_order) VALUES ('papas-solas', 'Papas Solas', 6) ON CONFLICT (id) DO NOTHING;
INSERT INTO categories (id, label, sort_order) VALUES ('bebestibles', 'Bebestibles', 7) ON CONFLICT (id) DO NOTHING;

-- Productos
INSERT INTO products (id, name, description, price, category, image, allows_extras, restricted_to_salvador_allende, modifier_groups, sort_order) VALUES (
  'box-duo', 'Box Duo', 'Papas + 2 proteínas + 2 salsas + 2 toques frescos + 1 sazón', 10990, 'escoge-tu-box', '/images/box-aros-cebolla.jpg',
  true, false,
  '[{"id": "proteinas", "label": "Elige 2 Proteínas", "required": 2, "options": [{"id": "carne-mechada", "name": "Carne Mechada", "price": 0}, {"id": "pollo-mechado", "name": "Pollo Mechado", "price": 0}, {"id": "salchicha", "name": "Salchicha", "price": 0}, {"id": "carne-soya", "name": "Carne de Soya", "price": 0}]}, {"id": "salsas", "label": "Elige 2 Salsas", "required": 2, "options": [{"id": "salsa-empapados", "name": "Salsa Empapados", "price": 0}, {"id": "aceituna-salsa", "name": "Aceituna", "price": 0}, {"id": "ajo", "name": "Ajo", "price": 0}, {"id": "salsa-verde", "name": "Salsa Verde", "price": 0}, {"id": "albahaca", "name": "Albahaca", "price": 0}, {"id": "bbq", "name": "BBQ", "price": 0}, {"id": "tartara", "name": "Tártara", "price": 0}, {"id": "cheddar-salsa", "name": "Cheddar", "price": 0}, {"id": "queso-salsa", "name": "Queso", "price": 0}, {"id": "champinon-salsa", "name": "Champiñón", "price": 0}, {"id": "chile-picante", "name": "Chile Picante", "price": 0}]}, {"id": "toques", "label": "Elige 2 Toques Frescos", "required": 2, "options": [{"id": "aceituna-toque", "name": "Aceituna", "price": 0}, {"id": "choclo", "name": "Choclo", "price": 0}, {"id": "champinon-toque", "name": "Champiñón", "price": 0}, {"id": "morron", "name": "Morrón", "price": 0}, {"id": "cebolla-caramelizada", "name": "Cebolla Caramelizada", "price": 0}, {"id": "tomate-cherry", "name": "Tomate Cherry", "price": 0}, {"id": "aji-verde", "name": "Ají Verde", "price": 0}, {"id": "pepinillo", "name": "Pepinillo", "price": 0}]}, {"id": "sazon", "label": "Elige 1 Sazón", "required": 1, "options": [{"id": "cebollin", "name": "Cebollín", "price": 0}, {"id": "merken", "name": "Merkén", "price": 0}, {"id": "oregano", "name": "Orégano", "price": 0}, {"id": "pimienta", "name": "Pimienta", "price": 0}]}, {"id": "premium-box-duo", "label": "Proteína Premium (costo extra)", "required": 0, "options": [{"id": "tocino-premium", "name": "Tocino", "price": 1990}, {"id": "bocados-carne", "name": "Bocados de Carne (1 un)", "price": 690}, {"id": "chorizo", "name": "Chorizo (100 gr app)", "price": 1990}]}, {"id": "adicionales-box-duo", "label": "Adicionales (costo extra)", "required": 0, "options": [{"id": "aros-cebolla", "name": "Aros de Cebolla (3 un)", "price": 990}, {"id": "dedos-queso", "name": "Dedos de Queso (3 un)", "price": 1990}, {"id": "nuggets-extra", "name": "Nuggets (5 un)", "price": 1990}, {"id": "palta-extra", "name": "Palta", "price": 1000}, {"id": "salsa-extra", "name": "Salsa Extra", "price": 1000}, {"id": "toques-extra", "name": "Toques Frescos Extra", "price": 1000}, {"id": "vegana-dia", "name": "Vegana del Día", "price": 1490}]}]'::jsonb, 0
) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, description, price, category, image, allows_extras, restricted_to_salvador_allende, modifier_groups, sort_order) VALUES (
  'box-family', 'Box Family', 'Papas + 2 proteínas + 3 salsas + 3 toques frescos + 2 sazón', 16490, 'escoge-tu-box', '/images/box-grande.jpg',
  true, false,
  '[{"id": "proteinas", "label": "Elige 2 Proteínas", "required": 2, "options": [{"id": "carne-mechada", "name": "Carne Mechada", "price": 0}, {"id": "pollo-mechado", "name": "Pollo Mechado", "price": 0}, {"id": "salchicha", "name": "Salchicha", "price": 0}, {"id": "carne-soya", "name": "Carne de Soya", "price": 0}]}, {"id": "salsas", "label": "Elige 3 Salsas", "required": 3, "options": [{"id": "salsa-empapados", "name": "Salsa Empapados", "price": 0}, {"id": "aceituna-salsa", "name": "Aceituna", "price": 0}, {"id": "ajo", "name": "Ajo", "price": 0}, {"id": "salsa-verde", "name": "Salsa Verde", "price": 0}, {"id": "albahaca", "name": "Albahaca", "price": 0}, {"id": "bbq", "name": "BBQ", "price": 0}, {"id": "tartara", "name": "Tártara", "price": 0}, {"id": "cheddar-salsa", "name": "Cheddar", "price": 0}, {"id": "queso-salsa", "name": "Queso", "price": 0}, {"id": "champinon-salsa", "name": "Champiñón", "price": 0}, {"id": "chile-picante", "name": "Chile Picante", "price": 0}]}, {"id": "toques", "label": "Elige 3 Toques Frescos", "required": 3, "options": [{"id": "aceituna-toque", "name": "Aceituna", "price": 0}, {"id": "choclo", "name": "Choclo", "price": 0}, {"id": "champinon-toque", "name": "Champiñón", "price": 0}, {"id": "morron", "name": "Morrón", "price": 0}, {"id": "cebolla-caramelizada", "name": "Cebolla Caramelizada", "price": 0}, {"id": "tomate-cherry", "name": "Tomate Cherry", "price": 0}, {"id": "aji-verde", "name": "Ají Verde", "price": 0}, {"id": "pepinillo", "name": "Pepinillo", "price": 0}]}, {"id": "sazon", "label": "Elige 2 Sazón", "required": 2, "options": [{"id": "cebollin", "name": "Cebollín", "price": 0}, {"id": "merken", "name": "Merkén", "price": 0}, {"id": "oregano", "name": "Orégano", "price": 0}, {"id": "pimienta", "name": "Pimienta", "price": 0}]}, {"id": "premium-box-family", "label": "Proteína Premium (costo extra)", "required": 0, "options": [{"id": "tocino-premium", "name": "Tocino", "price": 1990}, {"id": "bocados-carne", "name": "Bocados de Carne (1 un)", "price": 690}, {"id": "chorizo", "name": "Chorizo (100 gr app)", "price": 1990}]}, {"id": "adicionales-box-family", "label": "Adicionales (costo extra)", "required": 0, "options": [{"id": "aros-cebolla", "name": "Aros de Cebolla (3 un)", "price": 990}, {"id": "dedos-queso", "name": "Dedos de Queso (3 un)", "price": 1990}, {"id": "nuggets-extra", "name": "Nuggets (5 un)", "price": 1990}, {"id": "palta-extra", "name": "Palta", "price": 1000}, {"id": "salsa-extra", "name": "Salsa Extra", "price": 1000}, {"id": "toques-extra", "name": "Toques Frescos Extra", "price": 1000}, {"id": "vegana-dia", "name": "Vegana del Día", "price": 1490}]}]'::jsonb, 1
) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, description, price, category, image, allows_extras, restricted_to_salvador_allende, modifier_groups, sort_order) VALUES (
  'box-fiesta', 'Box Fiesta', 'Papas + 3 proteínas + 4 salsas + 4 toques frescos + 2 sazón', 19990, 'escoge-tu-box', '/images/box-grande-b.jpg',
  true, false,
  '[{"id": "proteinas", "label": "Elige 3 Proteínas", "required": 3, "options": [{"id": "carne-mechada", "name": "Carne Mechada", "price": 0}, {"id": "pollo-mechado", "name": "Pollo Mechado", "price": 0}, {"id": "salchicha", "name": "Salchicha", "price": 0}, {"id": "carne-soya", "name": "Carne de Soya", "price": 0}]}, {"id": "salsas", "label": "Elige 4 Salsas", "required": 4, "options": [{"id": "salsa-empapados", "name": "Salsa Empapados", "price": 0}, {"id": "aceituna-salsa", "name": "Aceituna", "price": 0}, {"id": "ajo", "name": "Ajo", "price": 0}, {"id": "salsa-verde", "name": "Salsa Verde", "price": 0}, {"id": "albahaca", "name": "Albahaca", "price": 0}, {"id": "bbq", "name": "BBQ", "price": 0}, {"id": "tartara", "name": "Tártara", "price": 0}, {"id": "cheddar-salsa", "name": "Cheddar", "price": 0}, {"id": "queso-salsa", "name": "Queso", "price": 0}, {"id": "champinon-salsa", "name": "Champiñón", "price": 0}, {"id": "chile-picante", "name": "Chile Picante", "price": 0}]}, {"id": "toques", "label": "Elige 4 Toques Frescos", "required": 4, "options": [{"id": "aceituna-toque", "name": "Aceituna", "price": 0}, {"id": "choclo", "name": "Choclo", "price": 0}, {"id": "champinon-toque", "name": "Champiñón", "price": 0}, {"id": "morron", "name": "Morrón", "price": 0}, {"id": "cebolla-caramelizada", "name": "Cebolla Caramelizada", "price": 0}, {"id": "tomate-cherry", "name": "Tomate Cherry", "price": 0}, {"id": "aji-verde", "name": "Ají Verde", "price": 0}, {"id": "pepinillo", "name": "Pepinillo", "price": 0}]}, {"id": "sazon", "label": "Elige 2 Sazón", "required": 2, "options": [{"id": "cebollin", "name": "Cebollín", "price": 0}, {"id": "merken", "name": "Merkén", "price": 0}, {"id": "oregano", "name": "Orégano", "price": 0}, {"id": "pimienta", "name": "Pimienta", "price": 0}]}, {"id": "premium-box-fiesta", "label": "Proteína Premium (costo extra)", "required": 0, "options": [{"id": "tocino-premium", "name": "Tocino", "price": 1990}, {"id": "bocados-carne", "name": "Bocados de Carne (1 un)", "price": 690}, {"id": "chorizo", "name": "Chorizo (100 gr app)", "price": 1990}]}, {"id": "adicionales-box-fiesta", "label": "Adicionales (costo extra)", "required": 0, "options": [{"id": "aros-cebolla", "name": "Aros de Cebolla (3 un)", "price": 990}, {"id": "dedos-queso", "name": "Dedos de Queso (3 un)", "price": 1990}, {"id": "nuggets-extra", "name": "Nuggets (5 un)", "price": 1990}, {"id": "palta-extra", "name": "Palta", "price": 1000}, {"id": "salsa-extra", "name": "Salsa Extra", "price": 1000}, {"id": "toques-extra", "name": "Toques Frescos Extra", "price": 1000}, {"id": "vegana-dia", "name": "Vegana del Día", "price": 1490}]}]'::jsonb, 2
) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, description, price, category, image, allows_extras, restricted_to_salvador_allende, modifier_groups, sort_order) VALUES (
  'box-ninos', 'Box Niños', 'Papas + Nuggets o Salchicha + 1 salsa', 7990, 'escoge-tu-box', '/images/box-aros-cebolla.jpg',
  true, false,
  '[{"id": "nuggets-salchicha", "label": "Elige 1: Nuggets o Salchicha", "required": 1, "options": [{"id": "nuggets-kids", "name": "Nuggets", "price": 0}, {"id": "salchicha-kids", "name": "Salchicha", "price": 0}]}, {"id": "salsas", "label": "Elige 1 Salsa", "required": 1, "options": [{"id": "salsa-empapados", "name": "Salsa Empapados", "price": 0}, {"id": "aceituna-salsa", "name": "Aceituna", "price": 0}, {"id": "ajo", "name": "Ajo", "price": 0}, {"id": "salsa-verde", "name": "Salsa Verde", "price": 0}, {"id": "albahaca", "name": "Albahaca", "price": 0}, {"id": "bbq", "name": "BBQ", "price": 0}, {"id": "tartara", "name": "Tártara", "price": 0}, {"id": "cheddar-salsa", "name": "Cheddar", "price": 0}, {"id": "queso-salsa", "name": "Queso", "price": 0}, {"id": "champinon-salsa", "name": "Champiñón", "price": 0}, {"id": "chile-picante", "name": "Chile Picante", "price": 0}]}, {"id": "adicionales-box-ninos", "label": "Adicionales (costo extra)", "required": 0, "options": [{"id": "aros-cebolla", "name": "Aros de Cebolla (3 un)", "price": 990}, {"id": "dedos-queso", "name": "Dedos de Queso (3 un)", "price": 1990}, {"id": "nuggets-extra", "name": "Nuggets (5 un)", "price": 1990}, {"id": "palta-extra", "name": "Palta", "price": 1000}, {"id": "salsa-extra", "name": "Salsa Extra", "price": 1000}, {"id": "toques-extra", "name": "Toques Frescos Extra", "price": 1000}, {"id": "vegana-dia", "name": "Vegana del Día", "price": 1490}]}]'::jsonb, 3
) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, description, price, category, image, allows_extras, restricted_to_salvador_allende, modifier_groups, sort_order) VALUES (
  'box-cheddar-duo', 'Box Cheddar Duo', 'Papas + salsa cheddar premium + tocino + 1 sazón', 9990, 'box-cheddar', '/images/box-cheddar-duo.jpg',
  true, false,
  '[{"id": "sazon", "label": "Elige 1 Sazón", "required": 1, "options": [{"id": "cebollin", "name": "Cebollín", "price": 0}, {"id": "merken", "name": "Merkén", "price": 0}, {"id": "oregano", "name": "Orégano", "price": 0}, {"id": "pimienta", "name": "Pimienta", "price": 0}]}, {"id": "adicionales-box-cheddar-duo", "label": "Adicionales (costo extra)", "required": 0, "options": [{"id": "aros-cebolla", "name": "Aros de Cebolla (3 un)", "price": 990}, {"id": "dedos-queso", "name": "Dedos de Queso (3 un)", "price": 1990}, {"id": "nuggets-extra", "name": "Nuggets (5 un)", "price": 1990}, {"id": "palta-extra", "name": "Palta", "price": 1000}, {"id": "salsa-extra", "name": "Salsa Extra", "price": 1000}, {"id": "toques-extra", "name": "Toques Frescos Extra", "price": 1000}, {"id": "vegana-dia", "name": "Vegana del Día", "price": 1490}]}]'::jsonb, 4
) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, description, price, category, image, allows_extras, restricted_to_salvador_allende, modifier_groups, sort_order) VALUES (
  'box-cheddar-family', 'Box Cheddar Family', 'Papas + salsa cheddar premium + tocino + 2 sazón', 14990, 'box-cheddar', '/images/box-cheddar-tocino.jpg',
  true, false,
  '[{"id": "sazon", "label": "Elige 2 Sazón", "required": 2, "options": [{"id": "cebollin", "name": "Cebollín", "price": 0}, {"id": "merken", "name": "Merkén", "price": 0}, {"id": "oregano", "name": "Orégano", "price": 0}, {"id": "pimienta", "name": "Pimienta", "price": 0}]}, {"id": "adicionales-box-cheddar-family", "label": "Adicionales (costo extra)", "required": 0, "options": [{"id": "aros-cebolla", "name": "Aros de Cebolla (3 un)", "price": 990}, {"id": "dedos-queso", "name": "Dedos de Queso (3 un)", "price": 1990}, {"id": "nuggets-extra", "name": "Nuggets (5 un)", "price": 1990}, {"id": "palta-extra", "name": "Palta", "price": 1000}, {"id": "salsa-extra", "name": "Salsa Extra", "price": 1000}, {"id": "toques-extra", "name": "Toques Frescos Extra", "price": 1000}, {"id": "vegana-dia", "name": "Vegana del Día", "price": 1490}]}]'::jsonb, 5
) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, description, price, category, image, allows_extras, restricted_to_salvador_allende, modifier_groups, sort_order) VALUES (
  'box-cheddar-fiesta', 'Box Cheddar Fiesta', 'Papas + salsa cheddar premium + tocino + 2 sazón', 17990, 'box-cheddar', '/images/box-cheddar-tocino.jpg',
  true, false,
  '[{"id": "sazon", "label": "Elige 2 Sazón", "required": 2, "options": [{"id": "cebollin", "name": "Cebollín", "price": 0}, {"id": "merken", "name": "Merkén", "price": 0}, {"id": "oregano", "name": "Orégano", "price": 0}, {"id": "pimienta", "name": "Pimienta", "price": 0}]}, {"id": "adicionales-box-cheddar-fiesta", "label": "Adicionales (costo extra)", "required": 0, "options": [{"id": "aros-cebolla", "name": "Aros de Cebolla (3 un)", "price": 990}, {"id": "dedos-queso", "name": "Dedos de Queso (3 un)", "price": 1990}, {"id": "nuggets-extra", "name": "Nuggets (5 un)", "price": 1990}, {"id": "palta-extra", "name": "Palta", "price": 1000}, {"id": "salsa-extra", "name": "Salsa Extra", "price": 1000}, {"id": "toques-extra", "name": "Toques Frescos Extra", "price": 1000}, {"id": "vegana-dia", "name": "Vegana del Día", "price": 1490}]}]'::jsonb, 6
) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, description, price, category, image, allows_extras, restricted_to_salvador_allende, modifier_groups, sort_order) VALUES (
  'cono-s', 'Cono S', 'Papas + 2 salsas + 1 sazón', 1990, 'conos', '/images/box-aros-cebolla.jpg',
  true, false,
  '[{"id": "salsas", "label": "Elige 2 Salsas", "required": 2, "options": [{"id": "salsa-empapados", "name": "Salsa Empapados", "price": 0}, {"id": "aceituna-salsa", "name": "Aceituna", "price": 0}, {"id": "ajo", "name": "Ajo", "price": 0}, {"id": "salsa-verde", "name": "Salsa Verde", "price": 0}, {"id": "albahaca", "name": "Albahaca", "price": 0}, {"id": "bbq", "name": "BBQ", "price": 0}, {"id": "tartara", "name": "Tártara", "price": 0}, {"id": "cheddar-salsa", "name": "Cheddar", "price": 0}, {"id": "queso-salsa", "name": "Queso", "price": 0}, {"id": "champinon-salsa", "name": "Champiñón", "price": 0}, {"id": "chile-picante", "name": "Chile Picante", "price": 0}]}, {"id": "sazon", "label": "Elige 1 Sazón", "required": 1, "options": [{"id": "cebollin", "name": "Cebollín", "price": 0}, {"id": "merken", "name": "Merkén", "price": 0}, {"id": "oregano", "name": "Orégano", "price": 0}, {"id": "pimienta", "name": "Pimienta", "price": 0}]}, {"id": "adicionales-cono-s", "label": "Adicionales (costo extra)", "required": 0, "options": [{"id": "aros-cebolla", "name": "Aros de Cebolla (3 un)", "price": 990}, {"id": "dedos-queso", "name": "Dedos de Queso (3 un)", "price": 1990}, {"id": "nuggets-extra", "name": "Nuggets (5 un)", "price": 1990}, {"id": "palta-extra", "name": "Palta", "price": 1000}, {"id": "salsa-extra", "name": "Salsa Extra", "price": 1000}, {"id": "toques-extra", "name": "Toques Frescos Extra", "price": 1000}, {"id": "vegana-dia", "name": "Vegana del Día", "price": 1490}]}]'::jsonb, 7
) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, description, price, category, image, allows_extras, restricted_to_salvador_allende, modifier_groups, sort_order) VALUES (
  'cono-m', 'Cono M', 'Papas + 2 salsas + 1 proteína + 1 toque fresco + 1 sazón', 3990, 'conos', '/images/cono-palta.jpg',
  true, false,
  '[{"id": "proteinas", "label": "Elige 1 Proteína", "required": 1, "options": [{"id": "carne-mechada", "name": "Carne Mechada", "price": 0}, {"id": "pollo-mechado", "name": "Pollo Mechado", "price": 0}, {"id": "salchicha", "name": "Salchicha", "price": 0}, {"id": "carne-soya", "name": "Carne de Soya", "price": 0}]}, {"id": "salsas", "label": "Elige 2 Salsas", "required": 2, "options": [{"id": "salsa-empapados", "name": "Salsa Empapados", "price": 0}, {"id": "aceituna-salsa", "name": "Aceituna", "price": 0}, {"id": "ajo", "name": "Ajo", "price": 0}, {"id": "salsa-verde", "name": "Salsa Verde", "price": 0}, {"id": "albahaca", "name": "Albahaca", "price": 0}, {"id": "bbq", "name": "BBQ", "price": 0}, {"id": "tartara", "name": "Tártara", "price": 0}, {"id": "cheddar-salsa", "name": "Cheddar", "price": 0}, {"id": "queso-salsa", "name": "Queso", "price": 0}, {"id": "champinon-salsa", "name": "Champiñón", "price": 0}, {"id": "chile-picante", "name": "Chile Picante", "price": 0}]}, {"id": "toques", "label": "Elige 1 Toque Fresco", "required": 1, "options": [{"id": "aceituna-toque", "name": "Aceituna", "price": 0}, {"id": "choclo", "name": "Choclo", "price": 0}, {"id": "champinon-toque", "name": "Champiñón", "price": 0}, {"id": "morron", "name": "Morrón", "price": 0}, {"id": "cebolla-caramelizada", "name": "Cebolla Caramelizada", "price": 0}, {"id": "tomate-cherry", "name": "Tomate Cherry", "price": 0}, {"id": "aji-verde", "name": "Ají Verde", "price": 0}, {"id": "pepinillo", "name": "Pepinillo", "price": 0}]}, {"id": "sazon", "label": "Elige 1 Sazón", "required": 1, "options": [{"id": "cebollin", "name": "Cebollín", "price": 0}, {"id": "merken", "name": "Merkén", "price": 0}, {"id": "oregano", "name": "Orégano", "price": 0}, {"id": "pimienta", "name": "Pimienta", "price": 0}]}, {"id": "premium-cono-m", "label": "Proteína Premium (costo extra)", "required": 0, "options": [{"id": "tocino-premium", "name": "Tocino", "price": 1990}, {"id": "bocados-carne", "name": "Bocados de Carne (1 un)", "price": 690}, {"id": "chorizo", "name": "Chorizo (100 gr app)", "price": 1990}]}, {"id": "adicionales-cono-m", "label": "Adicionales (costo extra)", "required": 0, "options": [{"id": "aros-cebolla", "name": "Aros de Cebolla (3 un)", "price": 990}, {"id": "dedos-queso", "name": "Dedos de Queso (3 un)", "price": 1990}, {"id": "nuggets-extra", "name": "Nuggets (5 un)", "price": 1990}, {"id": "palta-extra", "name": "Palta", "price": 1000}, {"id": "salsa-extra", "name": "Salsa Extra", "price": 1000}, {"id": "toques-extra", "name": "Toques Frescos Extra", "price": 1000}, {"id": "vegana-dia", "name": "Vegana del Día", "price": 1490}]}]'::jsonb, 8
) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, description, price, category, image, allows_extras, restricted_to_salvador_allende, modifier_groups, sort_order) VALUES (
  'cono-xl', 'Cono XL', 'Papas + 2 salsas + 1 proteína + 2 toques frescos + 1 sazón', 6990, 'conos', '/images/cono-mixto.jpg',
  true, false,
  '[{"id": "proteinas", "label": "Elige 1 Proteína", "required": 1, "options": [{"id": "carne-mechada", "name": "Carne Mechada", "price": 0}, {"id": "pollo-mechado", "name": "Pollo Mechado", "price": 0}, {"id": "salchicha", "name": "Salchicha", "price": 0}, {"id": "carne-soya", "name": "Carne de Soya", "price": 0}]}, {"id": "salsas", "label": "Elige 2 Salsas", "required": 2, "options": [{"id": "salsa-empapados", "name": "Salsa Empapados", "price": 0}, {"id": "aceituna-salsa", "name": "Aceituna", "price": 0}, {"id": "ajo", "name": "Ajo", "price": 0}, {"id": "salsa-verde", "name": "Salsa Verde", "price": 0}, {"id": "albahaca", "name": "Albahaca", "price": 0}, {"id": "bbq", "name": "BBQ", "price": 0}, {"id": "tartara", "name": "Tártara", "price": 0}, {"id": "cheddar-salsa", "name": "Cheddar", "price": 0}, {"id": "queso-salsa", "name": "Queso", "price": 0}, {"id": "champinon-salsa", "name": "Champiñón", "price": 0}, {"id": "chile-picante", "name": "Chile Picante", "price": 0}]}, {"id": "toques", "label": "Elige 2 Toques Frescos", "required": 2, "options": [{"id": "aceituna-toque", "name": "Aceituna", "price": 0}, {"id": "choclo", "name": "Choclo", "price": 0}, {"id": "champinon-toque", "name": "Champiñón", "price": 0}, {"id": "morron", "name": "Morrón", "price": 0}, {"id": "cebolla-caramelizada", "name": "Cebolla Caramelizada", "price": 0}, {"id": "tomate-cherry", "name": "Tomate Cherry", "price": 0}, {"id": "aji-verde", "name": "Ají Verde", "price": 0}, {"id": "pepinillo", "name": "Pepinillo", "price": 0}]}, {"id": "sazon", "label": "Elige 1 Sazón", "required": 1, "options": [{"id": "cebollin", "name": "Cebollín", "price": 0}, {"id": "merken", "name": "Merkén", "price": 0}, {"id": "oregano", "name": "Orégano", "price": 0}, {"id": "pimienta", "name": "Pimienta", "price": 0}]}, {"id": "premium-cono-xl", "label": "Proteína Premium (costo extra)", "required": 0, "options": [{"id": "tocino-premium", "name": "Tocino", "price": 1990}, {"id": "bocados-carne", "name": "Bocados de Carne (1 un)", "price": 690}, {"id": "chorizo", "name": "Chorizo (100 gr app)", "price": 1990}]}, {"id": "adicionales-cono-xl", "label": "Adicionales (costo extra)", "required": 0, "options": [{"id": "aros-cebolla", "name": "Aros de Cebolla (3 un)", "price": 990}, {"id": "dedos-queso", "name": "Dedos de Queso (3 un)", "price": 1990}, {"id": "nuggets-extra", "name": "Nuggets (5 un)", "price": 1990}, {"id": "palta-extra", "name": "Palta", "price": 1000}, {"id": "salsa-extra", "name": "Salsa Extra", "price": 1000}, {"id": "toques-extra", "name": "Toques Frescos Extra", "price": 1000}, {"id": "vegana-dia", "name": "Vegana del Día", "price": 1490}]}]'::jsonb, 9
) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, description, price, category, image, allows_extras, restricted_to_salvador_allende, modifier_groups, sort_order) VALUES (
  'box-burger-duo', 'Box Burger Duo', '2 cheese burger + papas + 1 salsa', 10990, 'box-burger', '/images/box-burger-duo-a.jpg',
  true, false,
  '[{"id": "salsas", "label": "Elige 1 Salsa", "required": 1, "options": [{"id": "salsa-empapados", "name": "Salsa Empapados", "price": 0}, {"id": "aceituna-salsa", "name": "Aceituna", "price": 0}, {"id": "ajo", "name": "Ajo", "price": 0}, {"id": "salsa-verde", "name": "Salsa Verde", "price": 0}, {"id": "albahaca", "name": "Albahaca", "price": 0}, {"id": "bbq", "name": "BBQ", "price": 0}, {"id": "tartara", "name": "Tártara", "price": 0}, {"id": "cheddar-salsa", "name": "Cheddar", "price": 0}, {"id": "queso-salsa", "name": "Queso", "price": 0}, {"id": "champinon-salsa", "name": "Champiñón", "price": 0}, {"id": "chile-picante", "name": "Chile Picante", "price": 0}]}, {"id": "adicionales-box-burger-duo", "label": "Adicionales (costo extra)", "required": 0, "options": [{"id": "aros-cebolla", "name": "Aros de Cebolla (3 un)", "price": 990}, {"id": "dedos-queso", "name": "Dedos de Queso (3 un)", "price": 1990}, {"id": "nuggets-extra", "name": "Nuggets (5 un)", "price": 1990}, {"id": "palta-extra", "name": "Palta", "price": 1000}, {"id": "salsa-extra", "name": "Salsa Extra", "price": 1000}, {"id": "toques-extra", "name": "Toques Frescos Extra", "price": 1000}, {"id": "vegana-dia", "name": "Vegana del Día", "price": 1490}]}]'::jsonb, 10
) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, description, price, category, image, allows_extras, restricted_to_salvador_allende, modifier_groups, sort_order) VALUES (
  'box-burger-family', 'Box Burger Family', '4 cheese burger + papas + 1 salsa', 15990, 'box-burger', '/images/box-burger-duo-b.jpg',
  true, false,
  '[{"id": "salsas", "label": "Elige 1 Salsa", "required": 1, "options": [{"id": "salsa-empapados", "name": "Salsa Empapados", "price": 0}, {"id": "aceituna-salsa", "name": "Aceituna", "price": 0}, {"id": "ajo", "name": "Ajo", "price": 0}, {"id": "salsa-verde", "name": "Salsa Verde", "price": 0}, {"id": "albahaca", "name": "Albahaca", "price": 0}, {"id": "bbq", "name": "BBQ", "price": 0}, {"id": "tartara", "name": "Tártara", "price": 0}, {"id": "cheddar-salsa", "name": "Cheddar", "price": 0}, {"id": "queso-salsa", "name": "Queso", "price": 0}, {"id": "champinon-salsa", "name": "Champiñón", "price": 0}, {"id": "chile-picante", "name": "Chile Picante", "price": 0}]}, {"id": "adicionales-box-burger-family", "label": "Adicionales (costo extra)", "required": 0, "options": [{"id": "aros-cebolla", "name": "Aros de Cebolla (3 un)", "price": 990}, {"id": "dedos-queso", "name": "Dedos de Queso (3 un)", "price": 1990}, {"id": "nuggets-extra", "name": "Nuggets (5 un)", "price": 1990}, {"id": "palta-extra", "name": "Palta", "price": 1000}, {"id": "salsa-extra", "name": "Salsa Extra", "price": 1000}, {"id": "toques-extra", "name": "Toques Frescos Extra", "price": 1000}, {"id": "vegana-dia", "name": "Vegana del Día", "price": 1490}]}]'::jsonb, 11
) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, description, price, category, image, allows_extras, restricted_to_salvador_allende, modifier_groups, sort_order) VALUES (
  'box-burger-fiesta', 'Box Burger Fiesta', '6 cheese burger + papas + 2 salsas', 22990, 'box-burger', '/images/box-burger-duo-b.jpg',
  true, false,
  '[{"id": "salsas", "label": "Elige 2 Salsas", "required": 2, "options": [{"id": "salsa-empapados", "name": "Salsa Empapados", "price": 0}, {"id": "aceituna-salsa", "name": "Aceituna", "price": 0}, {"id": "ajo", "name": "Ajo", "price": 0}, {"id": "salsa-verde", "name": "Salsa Verde", "price": 0}, {"id": "albahaca", "name": "Albahaca", "price": 0}, {"id": "bbq", "name": "BBQ", "price": 0}, {"id": "tartara", "name": "Tártara", "price": 0}, {"id": "cheddar-salsa", "name": "Cheddar", "price": 0}, {"id": "queso-salsa", "name": "Queso", "price": 0}, {"id": "champinon-salsa", "name": "Champiñón", "price": 0}, {"id": "chile-picante", "name": "Chile Picante", "price": 0}]}, {"id": "adicionales-box-burger-fiesta", "label": "Adicionales (costo extra)", "required": 0, "options": [{"id": "aros-cebolla", "name": "Aros de Cebolla (3 un)", "price": 990}, {"id": "dedos-queso", "name": "Dedos de Queso (3 un)", "price": 1990}, {"id": "nuggets-extra", "name": "Nuggets (5 un)", "price": 1990}, {"id": "palta-extra", "name": "Palta", "price": 1000}, {"id": "salsa-extra", "name": "Salsa Extra", "price": 1000}, {"id": "toques-extra", "name": "Toques Frescos Extra", "price": 1000}, {"id": "vegana-dia", "name": "Vegana del Día", "price": 1490}]}]'::jsonb, 12
) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, description, price, category, image, allows_extras, restricted_to_salvador_allende, modifier_groups, sort_order) VALUES (
  'sandwich-italiano', 'Sandwich Italiano', 'Palta, tomate, mayo + 1 salsa', 7490, 'sandwich', '/images/sandwich-italiano.jpg',
  true, true,
  '[{"id": "salsas", "label": "Elige 1 Salsa", "required": 1, "options": [{"id": "salsa-empapados", "name": "Salsa Empapados", "price": 0}, {"id": "aceituna-salsa", "name": "Aceituna", "price": 0}, {"id": "ajo", "name": "Ajo", "price": 0}, {"id": "salsa-verde", "name": "Salsa Verde", "price": 0}, {"id": "albahaca", "name": "Albahaca", "price": 0}, {"id": "bbq", "name": "BBQ", "price": 0}, {"id": "tartara", "name": "Tártara", "price": 0}, {"id": "cheddar-salsa", "name": "Cheddar", "price": 0}, {"id": "queso-salsa", "name": "Queso", "price": 0}, {"id": "champinon-salsa", "name": "Champiñón", "price": 0}, {"id": "chile-picante", "name": "Chile Picante", "price": 0}]}, {"id": "adicionales-sandwich-italiano", "label": "Adicionales (costo extra)", "required": 0, "options": [{"id": "aros-cebolla", "name": "Aros de Cebolla (3 un)", "price": 990}, {"id": "dedos-queso", "name": "Dedos de Queso (3 un)", "price": 1990}, {"id": "nuggets-extra", "name": "Nuggets (5 un)", "price": 1990}, {"id": "palta-extra", "name": "Palta", "price": 1000}, {"id": "salsa-extra", "name": "Salsa Extra", "price": 1000}, {"id": "toques-extra", "name": "Toques Frescos Extra", "price": 1000}, {"id": "vegana-dia", "name": "Vegana del Día", "price": 1490}]}]'::jsonb, 13
) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, description, price, category, image, allows_extras, restricted_to_salvador_allende, modifier_groups, sort_order) VALUES (
  'sandwich-aleman', 'Sandwich Alemán', 'Tomate, chucrut, pepinillo, mayo + 1 salsa', 7490, 'sandwich', '/images/sandwich-aleman.jpg',
  true, true,
  '[{"id": "salsas", "label": "Elige 1 Salsa", "required": 1, "options": [{"id": "salsa-empapados", "name": "Salsa Empapados", "price": 0}, {"id": "aceituna-salsa", "name": "Aceituna", "price": 0}, {"id": "ajo", "name": "Ajo", "price": 0}, {"id": "salsa-verde", "name": "Salsa Verde", "price": 0}, {"id": "albahaca", "name": "Albahaca", "price": 0}, {"id": "bbq", "name": "BBQ", "price": 0}, {"id": "tartara", "name": "Tártara", "price": 0}, {"id": "cheddar-salsa", "name": "Cheddar", "price": 0}, {"id": "queso-salsa", "name": "Queso", "price": 0}, {"id": "champinon-salsa", "name": "Champiñón", "price": 0}, {"id": "chile-picante", "name": "Chile Picante", "price": 0}]}, {"id": "adicionales-sandwich-aleman", "label": "Adicionales (costo extra)", "required": 0, "options": [{"id": "aros-cebolla", "name": "Aros de Cebolla (3 un)", "price": 990}, {"id": "dedos-queso", "name": "Dedos de Queso (3 un)", "price": 1990}, {"id": "nuggets-extra", "name": "Nuggets (5 un)", "price": 1990}, {"id": "palta-extra", "name": "Palta", "price": 1000}, {"id": "salsa-extra", "name": "Salsa Extra", "price": 1000}, {"id": "toques-extra", "name": "Toques Frescos Extra", "price": 1000}, {"id": "vegana-dia", "name": "Vegana del Día", "price": 1490}]}]'::jsonb, 14
) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, description, price, category, image, allows_extras, restricted_to_salvador_allende, modifier_groups, sort_order) VALUES (
  'sandwich-americano', 'Sandwich Americano a lo Pobre', 'Cebolla caramelizada, queso, huevo, salsa bbq', 8490, 'sandwich', '/images/sandwich-luco.jpg',
  true, true,
  '[{"id": "adicionales-sandwich-americano", "label": "Adicionales (costo extra)", "required": 0, "options": [{"id": "aros-cebolla", "name": "Aros de Cebolla (3 un)", "price": 990}, {"id": "dedos-queso", "name": "Dedos de Queso (3 un)", "price": 1990}, {"id": "nuggets-extra", "name": "Nuggets (5 un)", "price": 1990}, {"id": "palta-extra", "name": "Palta", "price": 1000}, {"id": "salsa-extra", "name": "Salsa Extra", "price": 1000}, {"id": "toques-extra", "name": "Toques Frescos Extra", "price": 1000}, {"id": "vegana-dia", "name": "Vegana del Día", "price": 1490}]}]'::jsonb, 15
) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, description, price, category, image, allows_extras, restricted_to_salvador_allende, modifier_groups, sort_order) VALUES (
  'sandwich-chacarero', 'Sandwich Chacarero', 'Poroto verde, ají verde, tomate, mayo + 1 salsa', 7490, 'sandwich', '/images/sandwich-chacarero.jpg',
  true, true,
  '[{"id": "salsas", "label": "Elige 1 Salsa", "required": 1, "options": [{"id": "salsa-empapados", "name": "Salsa Empapados", "price": 0}, {"id": "aceituna-salsa", "name": "Aceituna", "price": 0}, {"id": "ajo", "name": "Ajo", "price": 0}, {"id": "salsa-verde", "name": "Salsa Verde", "price": 0}, {"id": "albahaca", "name": "Albahaca", "price": 0}, {"id": "bbq", "name": "BBQ", "price": 0}, {"id": "tartara", "name": "Tártara", "price": 0}, {"id": "cheddar-salsa", "name": "Cheddar", "price": 0}, {"id": "queso-salsa", "name": "Queso", "price": 0}, {"id": "champinon-salsa", "name": "Champiñón", "price": 0}, {"id": "chile-picante", "name": "Chile Picante", "price": 0}]}, {"id": "adicionales-sandwich-chacarero", "label": "Adicionales (costo extra)", "required": 0, "options": [{"id": "aros-cebolla", "name": "Aros de Cebolla (3 un)", "price": 990}, {"id": "dedos-queso", "name": "Dedos de Queso (3 un)", "price": 1990}, {"id": "nuggets-extra", "name": "Nuggets (5 un)", "price": 1990}, {"id": "palta-extra", "name": "Palta", "price": 1000}, {"id": "salsa-extra", "name": "Salsa Extra", "price": 1000}, {"id": "toques-extra", "name": "Toques Frescos Extra", "price": 1000}, {"id": "vegana-dia", "name": "Vegana del Día", "price": 1490}]}]'::jsonb, 16
) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, description, price, category, image, allows_extras, restricted_to_salvador_allende, modifier_groups, sort_order) VALUES (
  'sandwich-empapado', 'Sandwich Empapado', 'Champiñón, palta, tocino, queso, mayo + 1 salsa', 8490, 'sandwich', '/images/sandwich-empapado.jpg',
  true, true,
  '[{"id": "salsas", "label": "Elige 1 Salsa", "required": 1, "options": [{"id": "salsa-empapados", "name": "Salsa Empapados", "price": 0}, {"id": "aceituna-salsa", "name": "Aceituna", "price": 0}, {"id": "ajo", "name": "Ajo", "price": 0}, {"id": "salsa-verde", "name": "Salsa Verde", "price": 0}, {"id": "albahaca", "name": "Albahaca", "price": 0}, {"id": "bbq", "name": "BBQ", "price": 0}, {"id": "tartara", "name": "Tártara", "price": 0}, {"id": "cheddar-salsa", "name": "Cheddar", "price": 0}, {"id": "queso-salsa", "name": "Queso", "price": 0}, {"id": "champinon-salsa", "name": "Champiñón", "price": 0}, {"id": "chile-picante", "name": "Chile Picante", "price": 0}]}, {"id": "adicionales-sandwich-empapado", "label": "Adicionales (costo extra)", "required": 0, "options": [{"id": "aros-cebolla", "name": "Aros de Cebolla (3 un)", "price": 990}, {"id": "dedos-queso", "name": "Dedos de Queso (3 un)", "price": 1990}, {"id": "nuggets-extra", "name": "Nuggets (5 un)", "price": 1990}, {"id": "palta-extra", "name": "Palta", "price": 1000}, {"id": "salsa-extra", "name": "Salsa Extra", "price": 1000}, {"id": "toques-extra", "name": "Toques Frescos Extra", "price": 1000}, {"id": "vegana-dia", "name": "Vegana del Día", "price": 1490}]}]'::jsonb, 17
) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, description, price, category, image, allows_extras, restricted_to_salvador_allende, modifier_groups, sort_order) VALUES (
  'sandwich-luco', 'Sandwich Luco Especial', 'Queso, palta + 1 salsa', 6990, 'sandwich', '/images/sandwich-luco.jpg',
  true, true,
  '[{"id": "salsas", "label": "Elige 1 Salsa", "required": 1, "options": [{"id": "salsa-empapados", "name": "Salsa Empapados", "price": 0}, {"id": "aceituna-salsa", "name": "Aceituna", "price": 0}, {"id": "ajo", "name": "Ajo", "price": 0}, {"id": "salsa-verde", "name": "Salsa Verde", "price": 0}, {"id": "albahaca", "name": "Albahaca", "price": 0}, {"id": "bbq", "name": "BBQ", "price": 0}, {"id": "tartara", "name": "Tártara", "price": 0}, {"id": "cheddar-salsa", "name": "Cheddar", "price": 0}, {"id": "queso-salsa", "name": "Queso", "price": 0}, {"id": "champinon-salsa", "name": "Champiñón", "price": 0}, {"id": "chile-picante", "name": "Chile Picante", "price": 0}]}, {"id": "adicionales-sandwich-luco", "label": "Adicionales (costo extra)", "required": 0, "options": [{"id": "aros-cebolla", "name": "Aros de Cebolla (3 un)", "price": 990}, {"id": "dedos-queso", "name": "Dedos de Queso (3 un)", "price": 1990}, {"id": "nuggets-extra", "name": "Nuggets (5 un)", "price": 1990}, {"id": "palta-extra", "name": "Palta", "price": 1000}, {"id": "salsa-extra", "name": "Salsa Extra", "price": 1000}, {"id": "toques-extra", "name": "Toques Frescos Extra", "price": 1000}, {"id": "vegana-dia", "name": "Vegana del Día", "price": 1490}]}]'::jsonb, 18
) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, description, price, category, image, allows_extras, restricted_to_salvador_allende, modifier_groups, sort_order) VALUES (
  'completo-aleman', 'Completo Alemán', 'Tomate, chucrut, pepinillo, mayo + 1 salsa', 2990, 'completos', '/images/completo-americano.jpg',
  true, true,
  '[{"id": "salsas", "label": "Elige 1 Salsa", "required": 1, "options": [{"id": "salsa-empapados", "name": "Salsa Empapados", "price": 0}, {"id": "aceituna-salsa", "name": "Aceituna", "price": 0}, {"id": "ajo", "name": "Ajo", "price": 0}, {"id": "salsa-verde", "name": "Salsa Verde", "price": 0}, {"id": "albahaca", "name": "Albahaca", "price": 0}, {"id": "bbq", "name": "BBQ", "price": 0}, {"id": "tartara", "name": "Tártara", "price": 0}, {"id": "cheddar-salsa", "name": "Cheddar", "price": 0}, {"id": "queso-salsa", "name": "Queso", "price": 0}, {"id": "champinon-salsa", "name": "Champiñón", "price": 0}, {"id": "chile-picante", "name": "Chile Picante", "price": 0}]}, {"id": "adicionales-completo-aleman", "label": "Adicionales (costo extra)", "required": 0, "options": [{"id": "aros-cebolla", "name": "Aros de Cebolla (3 un)", "price": 990}, {"id": "dedos-queso", "name": "Dedos de Queso (3 un)", "price": 1990}, {"id": "nuggets-extra", "name": "Nuggets (5 un)", "price": 1990}, {"id": "palta-extra", "name": "Palta", "price": 1000}, {"id": "salsa-extra", "name": "Salsa Extra", "price": 1000}, {"id": "toques-extra", "name": "Toques Frescos Extra", "price": 1000}, {"id": "vegana-dia", "name": "Vegana del Día", "price": 1490}]}]'::jsonb, 19
) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, description, price, category, image, allows_extras, restricted_to_salvador_allende, modifier_groups, sort_order) VALUES (
  'completo-americano', 'Completo Americano', 'Cebolla caramelizada, queso, salsa bbq', 3490, 'completos', '/images/completo-americano.jpg',
  true, true,
  '[{"id": "adicionales-completo-americano", "label": "Adicionales (costo extra)", "required": 0, "options": [{"id": "aros-cebolla", "name": "Aros de Cebolla (3 un)", "price": 990}, {"id": "dedos-queso", "name": "Dedos de Queso (3 un)", "price": 1990}, {"id": "nuggets-extra", "name": "Nuggets (5 un)", "price": 1990}, {"id": "palta-extra", "name": "Palta", "price": 1000}, {"id": "salsa-extra", "name": "Salsa Extra", "price": 1000}, {"id": "toques-extra", "name": "Toques Frescos Extra", "price": 1000}, {"id": "vegana-dia", "name": "Vegana del Día", "price": 1490}]}]'::jsonb, 20
) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, description, price, category, image, allows_extras, restricted_to_salvador_allende, modifier_groups, sort_order) VALUES (
  'completo-empapado', 'Completo Empapado', 'Champiñón, palta, tocino, queso, mayo + 1 salsa', 3490, 'completos', '/images/completo-americano.jpg',
  true, true,
  '[{"id": "salsas", "label": "Elige 1 Salsa", "required": 1, "options": [{"id": "salsa-empapados", "name": "Salsa Empapados", "price": 0}, {"id": "aceituna-salsa", "name": "Aceituna", "price": 0}, {"id": "ajo", "name": "Ajo", "price": 0}, {"id": "salsa-verde", "name": "Salsa Verde", "price": 0}, {"id": "albahaca", "name": "Albahaca", "price": 0}, {"id": "bbq", "name": "BBQ", "price": 0}, {"id": "tartara", "name": "Tártara", "price": 0}, {"id": "cheddar-salsa", "name": "Cheddar", "price": 0}, {"id": "queso-salsa", "name": "Queso", "price": 0}, {"id": "champinon-salsa", "name": "Champiñón", "price": 0}, {"id": "chile-picante", "name": "Chile Picante", "price": 0}]}, {"id": "adicionales-completo-empapado", "label": "Adicionales (costo extra)", "required": 0, "options": [{"id": "aros-cebolla", "name": "Aros de Cebolla (3 un)", "price": 990}, {"id": "dedos-queso", "name": "Dedos de Queso (3 un)", "price": 1990}, {"id": "nuggets-extra", "name": "Nuggets (5 un)", "price": 1990}, {"id": "palta-extra", "name": "Palta", "price": 1000}, {"id": "salsa-extra", "name": "Salsa Extra", "price": 1000}, {"id": "toques-extra", "name": "Toques Frescos Extra", "price": 1000}, {"id": "vegana-dia", "name": "Vegana del Día", "price": 1490}]}]'::jsonb, 21
) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, description, price, category, image, allows_extras, restricted_to_salvador_allende, modifier_groups, sort_order) VALUES (
  'completo-italiano', 'Completo Italiano', 'Palta, tomate, mayo + 1 salsa', 2990, 'completos', '/images/completo-americano.jpg',
  true, true,
  '[{"id": "salsas", "label": "Elige 1 Salsa", "required": 1, "options": [{"id": "salsa-empapados", "name": "Salsa Empapados", "price": 0}, {"id": "aceituna-salsa", "name": "Aceituna", "price": 0}, {"id": "ajo", "name": "Ajo", "price": 0}, {"id": "salsa-verde", "name": "Salsa Verde", "price": 0}, {"id": "albahaca", "name": "Albahaca", "price": 0}, {"id": "bbq", "name": "BBQ", "price": 0}, {"id": "tartara", "name": "Tártara", "price": 0}, {"id": "cheddar-salsa", "name": "Cheddar", "price": 0}, {"id": "queso-salsa", "name": "Queso", "price": 0}, {"id": "champinon-salsa", "name": "Champiñón", "price": 0}, {"id": "chile-picante", "name": "Chile Picante", "price": 0}]}, {"id": "adicionales-completo-italiano", "label": "Adicionales (costo extra)", "required": 0, "options": [{"id": "aros-cebolla", "name": "Aros de Cebolla (3 un)", "price": 990}, {"id": "dedos-queso", "name": "Dedos de Queso (3 un)", "price": 1990}, {"id": "nuggets-extra", "name": "Nuggets (5 un)", "price": 1990}, {"id": "palta-extra", "name": "Palta", "price": 1000}, {"id": "salsa-extra", "name": "Salsa Extra", "price": 1000}, {"id": "toques-extra", "name": "Toques Frescos Extra", "price": 1000}, {"id": "vegana-dia", "name": "Vegana del Día", "price": 1490}]}]'::jsonb, 22
) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, description, price, category, image, allows_extras, restricted_to_salvador_allende, modifier_groups, sort_order) VALUES (
  'completo-luco', 'Completo Luco Especial', 'Queso, palta + 1 salsa', 2990, 'completos', '/images/completo-americano.jpg',
  true, true,
  '[{"id": "salsas", "label": "Elige 1 Salsa", "required": 1, "options": [{"id": "salsa-empapados", "name": "Salsa Empapados", "price": 0}, {"id": "aceituna-salsa", "name": "Aceituna", "price": 0}, {"id": "ajo", "name": "Ajo", "price": 0}, {"id": "salsa-verde", "name": "Salsa Verde", "price": 0}, {"id": "albahaca", "name": "Albahaca", "price": 0}, {"id": "bbq", "name": "BBQ", "price": 0}, {"id": "tartara", "name": "Tártara", "price": 0}, {"id": "cheddar-salsa", "name": "Cheddar", "price": 0}, {"id": "queso-salsa", "name": "Queso", "price": 0}, {"id": "champinon-salsa", "name": "Champiñón", "price": 0}, {"id": "chile-picante", "name": "Chile Picante", "price": 0}]}, {"id": "adicionales-completo-luco", "label": "Adicionales (costo extra)", "required": 0, "options": [{"id": "aros-cebolla", "name": "Aros de Cebolla (3 un)", "price": 990}, {"id": "dedos-queso", "name": "Dedos de Queso (3 un)", "price": 1990}, {"id": "nuggets-extra", "name": "Nuggets (5 un)", "price": 1990}, {"id": "palta-extra", "name": "Palta", "price": 1000}, {"id": "salsa-extra", "name": "Salsa Extra", "price": 1000}, {"id": "toques-extra", "name": "Toques Frescos Extra", "price": 1000}, {"id": "vegana-dia", "name": "Vegana del Día", "price": 1490}]}]'::jsonb, 23
) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, description, price, category, image, allows_extras, restricted_to_salvador_allende, modifier_groups, sort_order) VALUES (
  'papas-solas-duo', 'Papas Solas Duo', 'Solo papas, formato duo', 6990, 'papas-solas', '/images/box-grande.jpg',
  false, false,
  '[]'::jsonb, 24
) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, description, price, category, image, allows_extras, restricted_to_salvador_allende, modifier_groups, sort_order) VALUES (
  'papas-solas-family', 'Papas Solas Family', 'Solo papas, formato family', 10990, 'papas-solas', '/images/box-grande-b.jpg',
  false, false,
  '[]'::jsonb, 25
) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, description, price, category, image, allows_extras, restricted_to_salvador_allende, modifier_groups, sort_order) VALUES (
  'papas-solas-cono2', 'Papas Solas Cono 2', 'Solo papas, cono pequeño', 1490, 'papas-solas', '/images/cono-mixto.jpg',
  false, false,
  '[]'::jsonb, 26
) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, description, price, category, image, allows_extras, restricted_to_salvador_allende, modifier_groups, sort_order) VALUES (
  'papas-solas-conom', 'Papas Solas Cono M', 'Solo papas, cono mediano', 1990, 'papas-solas', '/images/cono-palta.jpg',
  false, false,
  '[]'::jsonb, 27
) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, description, price, category, image, allows_extras, restricted_to_salvador_allende, modifier_groups, sort_order) VALUES (
  'papas-solas-conoxl', 'Papas Solas Cono XL', 'Solo papas, cono extra grande', 3990, 'papas-solas', '/images/box-aros-cebolla.jpg',
  false, false,
  '[]'::jsonb, 28
) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, description, price, category, image, allows_extras, restricted_to_salvador_allende, modifier_groups, sort_order) VALUES (
  'bebida-lata', 'Bebida Lata 220cc', 'Coca-Cola · Fanta · Sprite', 1500, 'bebestibles', NULL,
  false, false,
  '[]'::jsonb, 29
) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, description, price, category, image, allows_extras, restricted_to_salvador_allende, modifier_groups, sort_order) VALUES (
  'bebida-1.5', 'Bebida 1,5 Lt.', 'Coca-Cola · Fanta · Sprite', 2500, 'bebestibles', NULL,
  false, false,
  '[]'::jsonb, 30
) ON CONFLICT (id) DO NOTHING;
INSERT INTO products (id, name, description, price, category, image, allows_extras, restricted_to_salvador_allende, modifier_groups, sort_order) VALUES (
  'jugo-1.5', 'Jugo 1,5 Lt.', 'Jugo natural', 2500, 'bebestibles', NULL,
  false, false,
  '[]'::jsonb, 31
) ON CONFLICT (id) DO NOTHING;
